version: "3"
services:
  leads-app:
    container_name: leads-app
    build:
      context: .
      dockerfile: .Dockerfile
    depends_on:
      - postgres
    environment:
      DB_USER : postgres
      DB_HOST : localhost
      DB_NAME : crmleads
      DB_PASSWORD : postgres
      DB_PORT : 5432
      PORT: 8080
    ports:
      - "8080:8080"
  postgres:
    container_name: postgres
    image: postgres:lates
    ports:
      - "5432:5432"
    volumes: 
      - ./postgresdata:/var/lib/postgresql/data
      - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crmleads
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: sshyamlalchauhan@gmail
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
    db-data:
    pgadmin-data: